spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shiro_test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  thymeleaf:
    cache: false
    # 默认就是 /templates/ ，可以不配置
    prefix: classpath:/templates/web/
    # 默认就是 .html
    suffix: .html


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.woodwhales.king.model
logging:
  level:
    org.woodwhales.king: DEBUG
